name: "Build and Push Containers"

on:
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Image name
        id: name
        run: |
          echo "FQ_NAME=${FQ_NAME,,}" >> "$GITHUB_OUTPUT"   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build Dev Container
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3
        with:
          subFolder: ./src/base
          imageName: ${{ steps.name.outputs.FQ_NAME }}
          imageTag: base-${{ github.sha }}-${{ matrix.arch }}
          platform: linux/${{ matrix.arch }}
          refFilterForPush: 'refs/heads/main'
          eventFilterForPush: |
            merge_group
            workflow_dispatch
            schedule
          

      - name: Build and Push Titanoboa Dev Container
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ./src/titanoboa
          imageName: ${{ steps.name.outputs.FQ_NAME }}
          imageTag: titanoboa-${{ github.sha }}-${{ matrix.arch }}
          platform: linux/${{ matrix.arch }}
          refFilterForPush: 'refs/heads/main'
          eventFilterForPush: |
            merge_group
            workflow_dispatch
            schedule


  sign:
    if: github.event_name != 'pull_request'
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Lowercase Image Repo
        id: name
        run: echo "IMAGE_REPO=${IMAGE_REPO,,}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Sign Images
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${{ steps.name.outputs.IMAGE_REPO }}:base-${{ github.sha }}-${{ matrix.arch }}
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${{ steps.name.outputs.IMAGE_REPO }}:titanoboa-${{ github.sha }}-${{ matrix.arch }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  manifest:
    if: github.event_name != 'pull_request'
    needs: ["sign"]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase Image Repo
        id: name
        run: echo "FQ_NAME=${FQ_NAME,,}" >> "$GITHUB_OUTPUT"

      - name: Push Manifests
        run: |
          set -ex
          docker manifest create ${{ steps.name.outputs.FQ_NAME }}:latest \
            --amend ${{ steps.name.outputs.FQ_NAME }}:base-${{ github.sha }}-amd64 \
            --amend ${{ steps.name.outputs.FQ_NAME }}:base-${{ github.sha }}-arm64
          docker manifest push ${{ steps.name.outputs.FQ_NAME }}:latest

          docker manifest create ${{ steps.name.outputs.FQ_NAME }}:${{ github.sha }} \
            --amend ${{ steps.name.outputs.FQ_NAME }}:base-${{ github.sha }}-amd64 \
            --amend ${{ steps.name.outputs.FQ_NAME }}:base-${{ github.sha }}-arm64
          docker manifest push ${{ steps.name.outputs.FQ_NAME }}:${{ github.sha }}

          docker manifest create ${{ steps.name.outputs.FQ_NAME }}:titanoboa \
            --amend ${{ steps.name.outputs.FQ_NAME }}:t itanoboa-${{ github.sha }}-amd64 \
            --amend ${{ steps.name.outputs.FQ_NAME }}:titanoboa-${{ github.sha }}-arm64
          docker manifest push ${{ steps.name.outputs.FQ_NAME }}:titanoboa

          docker manifest create ${{ steps.name.outputs.FQ_NAME }}:titanoboa-${{ github.sha }} \
            --amend ${{ steps.name.outputs.FQ_NAME }}:titanoboa-${{ github.sha }}-amd64 \
            --amend ${{ steps.name.outputs.FQ_NAME }}:titanoboa-${{ github.sha }}-arm64
          docker manifest push ${{ steps.name.outputs.FQ_NAME }}:titanoboa-${{ github.sha }}
