name: 'build'
on:
    pull_request:
        branches:
            - main
    merge_group: 
    workflow_dispatch:
    schedule:
        - cron: "* * * * 0" # 0000 UTC Sunday
    
jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to GHCR
              if: contains(fromJson('["workflow_dispatch", "merge_group", "schedule"]'), github.event_name)
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ github.token }}
            
            - name: Build Dev Container
              uses: devcontainers/ci@v0.3
              with:
                imageName: ghcr.io/ublue-os/devcontainer
                eventFilterForPush: |
                    merge_group
                    workflow_dispatch
                    schedule
