name: 'build'
on:
    pull_request:
        branches:
            - main
    merge_group: 
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 0" # 0000 UTC Sunday
    
jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            
            - name: Login to GHCR
              if: contains(fromJson('["workflow_dispatch", "merge_group", "schedule"]'), github.event_name)
              uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ github.token }}
            
            - name: Build Dev Container
              uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3
              with:
                imageName: ghcr.io/ublue-os/devcontainer
                refFilterForPush: |
                    refs/heads/main
                eventFilterForPush: |
                    merge_group
                    workflow_dispatch
                    schedule
